- hosts: [mylb]
  vars:
          lbport_no: "8083" 

  tasks:
  - name: "Installing haproxy server .. "
    package:
      name: "haproxy"
      state: present
    register: z

  - name: "starting haproxy server"
    service:
      name: "haproxy"
      state: started
    when: z.changed != false
                                 

  - name: "configuring haproxy file"
    template:
      dest: "/etc/haproxy/haproxy.cfg"
      src: "haproxy.cfg"
    register: y
  
  - name: "restarting haproxy server"
    service:
      name: "haproxy"
      state: restarted
    when: y.changed != false


- hosts: [myweb]
  tasks:
  - name: "installing apache software"        
    package:
      name: "httpd"
      state: present
    register: http

  - name: "configuring apache file"  
    copy:
      src: "abhi.php"
      dest: "/var/www/html"
    register: mydoc

  - name: "starting apache server .."
    service:
      name: "httpd"
      state: started
    when: http.changed != false

  - name: "restarting apache server .."
    service:
      name: "httpd"
      state: restarted
    when: mydoc.changed != false

  - name: "installing php software .."
    package: 
      name: "php"
      state: present

  - name: "starting firewall services"
    service: 
      name: "firewalld"
      state: started

  - name: "enabling port for tcp .."    
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      immediate: yes
      
  - name: "restarting firewall services .."
    service:
      name: "firewalld"
      state: restarted

    
